name: Perl CI

on:
  push:
    branches: [ "develop", "master", "f/202405-pipeline-github" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: dependencies
      run: sudo apt-get install -y libmoose-perl libjson-perl libjson-maybexs-perl libwww-perl libreadonly-perl liblog-log4perl-perl liburi-encode-perl libconfig-ini-perl libdatetime-perl libdbd-mysql-perl libdbi-perl libtime-duration-perl libuniversal-require-perl libtest-deep-perl libtest-mockmodule-perl libcache-cache-perl
    - name: ExtUtils::MakeMaker
      run: perl Makefile.PL
    - name: make
      run: make
    - name: make test
      run: make test
